### ISSUE TITLE
batch processing error

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#163]
this is the first file

```
[zootaxa.4277.1.1.pdf](https://github.com/gsautter/goldengate-imagine/files/1146909/zootaxa.4277.1.1.pdf)

D:\GoldenGateImagine20170529>java -jar -Xmx9216m GgImagineBatch.jar "DATA=E:\diglib\zootaxa\2017\temp" DT=BD
Loading parameters
GoldenGATE Imagine core created, configuration is Default.imagine
Image Markup Tool 'StructureDetector' loaded
Image Markup Tool 'MetaDataAdder' loaded
Image Markup Tool 'KeyHandler' loaded
Image Markup Tool 'ParseBibliography.imTool' loaded
Image Markup Tool 'MarkBibRefCitations.imTool' loaded
Image Markup Tool 'MarkTaxonNames.imTool' loaded
Image Markup Tool 'TableAnnotCleaner' loaded
Image Markup Tool 'RemoveDuplicateAnnots' loaded
Image Markup Tool 'TreatmentTaggerStyled.imTool' loaded
Image Markup Tool 'ExtractMaterialsCitations.imTool' loaded
Image Markup Tool 'CheckAnnotNesting' loaded
Processing document 'E:\diglib\zootaxa\2017\temp\zootaxa.4277.1.1.pdf'
 - loaded PDF of 6259738 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Handling flipped page content
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Generating pages
Analyzing page structure
Analyzing text stream structure
 - PDF converted, document ID is 'FF9D9E280B09FFE6FFCDFFCF2E09A66D'
 - assigned document style 'zootaxa.2013.journal_article'
Running Image Markup Tool 'Detect Document Structure'
Detecting document structure from 16 pages
 - gathering data
 - scoring page numbers:
 - checking page number sequence:
 - filling in missing page numbers:
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - indexing paragraph end words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
 - identifying caption target areas
 - merging tables within pages
 - merging tables across pages
 - marking caption citations
Error processing document 'E:\diglib\zootaxa\2017\temp\zootaxa.4277.1.1.pdf': de.uka.ipd.idaho.im.ImSupplement$Graphics$1 cannot be cast to de.uka.ipd.idaho.im.ImSupplement$Figure
java.lang.ClassCastException: de.uka.ipd.idaho.im.ImSupplement$Graphics$1 cannot be cast to de.uka.ipd.idaho.im.ImSupplement$Figure
        at de.uka.ipd.idaho.im.imagine.plugins.util.CaptionCitationHandler.getCaptionTargetSupplementId(CaptionCitationHandler.java:715)
        at de.uka.ipd.idaho.im.imagine.plugins.util.CaptionCitationHandler.annotateCaptionCitation(CaptionCitationHandler.java:1379)
        at de.uka.ipd.idaho.im.imagine.plugins.util.CaptionCitationHandler.markCaptionCitation(CaptionCitationHandler.java:1122)
        at de.uka.ipd.idaho.im.imagine.plugins.util.CaptionCitationHandler.markCaptionCitations(CaptionCitationHandler.java:1054)
        at de.uka.ipd.idaho.im.imagine.plugins.util.CaptionCitationHandler.markCaptionCitations(CaptionCitationHandler.java:1035)
        at de.uka.ipd.idaho.im.imagine.plugins.util.CaptionCitationHandler.markCaptionCitations(CaptionCitationHandler.java:854)
        at de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStructureDetectorProvider.detectDocumentStructure(DocumentStructureDetectorProvider.java:1250)
        at de.uka.ipd.idaho.im.imagine.plugins.doc.DocumentStructureDetectorProvider$StructureDetector.process(DocumentStructureDetectorProvider.java:264)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:430)
Processing document 'E:\diglib\zootaxa\2017\temp\zootaxa.4277.1.10.pdf'
 - loaded PDF of 1049108 bytes
Extracting page content
Assessing font char usage
Importing page words
```

**Comment by gsautter** [comment]
Just sent you a hot fix JAR with a fix. The latter will of course also be in the next build.
