### ISSUE TITLE
new GGI  built does not load: bug 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#18]
@gsautter the new built does not work, starting of GGI is interrupted
[errorLog20161209_gsautter the new built of GGI does not load.pdf](https://github.com/gsautter/goldengate-imagine/files/641492/errorLog20161209_gsautter.the.new.built.of.GGI.does.not.load.pdf)

**Comment by gsautter** [comment]
Weird one ... the files reported missing are all in the build ZIPs, and at least GoldenGATE.cnfg is also on the server (see http://tb.plazi.org/GgServer/Configurations/Default.imagine/files.txt).

As to the logo, it's in the ZIPs, investigating why it's not listed above.

The log breaks off in what looks to me like a normal startup procedure, namely it's loading the plug-ins, and there is no error.

Does the error log say anything?

**Comment by myrmoteras** [comment]
Exception in thread "main" java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(Unknown Source)
	at de.uka.ipd.idaho.easyIO.help.HelpPanel$HelpCellRenderer.<init>(HelpPanel.java:1071)
	at de.uka.ipd.idaho.easyIO.help.HelpPanel.<init>(HelpPanel.java:170)
	at de.uka.ipd.idaho.easyIO.help.Help.<init>(Help.java:72)
	at de.uka.ipd.idaho.goldenGate.GoldenGATE.<init>(GoldenGATE.java:301)
	at de.uka.ipd.idaho.goldenGate.GoldenGATE.openGoldenGATE(GoldenGATE.java:3250)
	at de.uka.ipd.idaho.goldenGate.GoldenGATE.openGoldenGATE(GoldenGATE.java:3201)
	at de.uka.ipd.idaho.im.imagine.GoldenGateImagine.openGoldenGATE(GoldenGateImagine.java:1113)
	at de.uka.ipd.idaho.im.imagine.application.GoldenGateImagineApplication.main(GoldenGateImagineApplication.java:393)

**Comment by gsautter** [comment]
Oh, that's about the icon ... OK, that might be the reason, if one that should not be. Will check why that thing is even missing, as I cannot remember it ever being any kind of problem thus far. And I surely didn't change anything in that regard.

**Comment by myrmoteras** [comment]
this time it works, after a new download when I started the program

**Comment by gsautter** [comment]
There's something hinky with the Configurations servlet ... if anything fails again, you can download the whole configuration from http://tb.plazi.org/GgServer/Downloads/Default.imagine.zip .

Just drop that into <GGI>/Configurations/ and restart, it will be unzipped automatically.
