### ISSUE TITLE
converision interrrupted

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#2]
@gsautter can you please check this file. It stopped during conversion, using the build from 20161129

[Alther_et_al_2016.pdf](https://github.com/gsautter/goldengate-imagine/files/623923/Alther_et_al_2016.pdf)

Font 'FreeSerif' loaded successfully.
Font 'FreeSerifItalic' loaded successfully.
Font 'FreeSerifBold' loaded successfully.
Font 'FreeSerifBoldItalic' loaded successfully.
Font 'FreeSans' loaded successfully.
Font 'FreeSansOblique' loaded successfully.
Font 'FreeSansBold' loaded successfully.
Font 'FreeSansBoldOblique' loaded successfully.
Font 'FreeMono' loaded successfully.
Font 'FreeMonoOblique' loaded successfully.
Font 'FreeMonoBold' loaded successfully.
Font 'FreeMonoBoldOblique' loaded successfully.
Dec 01, 2016 8:32:33 AM org.icepdf.core.pobjects.Catalog <clinit>
INFO: ICEsoft ICEpdf Core 4.2.0 
Exception in thread "Thread-159" java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.image.BufferedImage.<init>(Unknown Source)
	at org.icepdf.core.pobjects.Document.getPageImage(Document.java:1034)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor.extractFigureFromPageImage(PdfExtractor.java:8053)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor.getFigureImage(PdfExtractor.java:948)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor.storeFiguresAsSupplements(PdfExtractor.java:3636)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor.access$400(PdfExtractor.java:157)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor$6.doFor(PdfExtractor.java:1375)
	at de.uka.ipd.idaho.gamta.util.ParallelJobRunner$ParallelForJob.run(ParallelJobRunner.java:245)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "LoaderThread" java.lang.NullPointerException
	at de.uka.ipd.idaho.im.pdf.PdfExtractor$8.doFor(PdfExtractor.java:1778)
	at de.uka.ipd.idaho.gamta.util.ParallelJobRunner$ParallelForJob.run(ParallelJobRunner.java:245)
	at java.lang.Thread.run(Unknown Source)

**Comment by gsautter** [comment]
Decodes now ... problem was a 4410 DPI (!!!) bitmap image ... that innocent little butterfly in the banner across the very top of the first page. Decoding that caused the page image to be rendered at that very resolution at times (when the default decoding approach fails), resulting in an inevitable out-of-memory problem in this case. Changed the alternative image decoding approach now.

Also, the phylogenertic tree on page 7 comes as a 1100 DPI (!) bitmap, rather than as vector graphics.

Never ceases to make me scratch my head at first, and shake it in disbelief after finding out what the problem is ...
