### ISSUE TITLE
does not process: zootaxa.4306.3.3

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#200]
https://drive.google.com/open?id=0B_yrQwn4yBySaWE0VUdmS1UyNXc

D:\GoldenGateImagine_20170221>java -jar -Xmx4096m GgImagineBatch.jar "DATA=D:\diglib\zootaxa\2017\temp1" DT=BD
Loading parameters
GoldenGATE Imagine core created, configuration is Default.imagine
Image Markup Tool 'StructureDetector' loaded
Image Markup Tool 'MetaDataAdder' loaded
Image Markup Tool 'KeyHandler' loaded
Image Markup Tool 'ParseBibliography.imTool' loaded
Image Markup Tool 'MarkBibRefCitations.imTool' loaded
Image Markup Tool 'MarkTaxonNames.imTool' loaded
Image Markup Tool 'TableAnnotCleaner' loaded
Image Markup Tool 'RemoveDuplicateAnnots' loaded
Image Markup Tool 'TreatmentTaggerStyled.imTool' loaded
Image Markup Tool 'ExtractMaterialsCitations.imTool' loaded
Image Markup Tool 'CheckAnnotNesting' loaded
Processing document 'D:\diglib\zootaxa\2017\temp1\zootaxa.4306.3.3.pdf'
 - loaded PDF of 39850710 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Handling flipped page content
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Error processing document 'D:\diglib\zootaxa\2017\temp1\zootaxa.4306.3.3.pdf': Error skipping PNG metadata
javax.imageio.IIOException: Error skipping PNG metadata
        at com.sun.imageio.plugins.png.PNGImageReader.readMetadata(Unknown Source)
        at com.sun.imageio.plugins.png.PNGImageReader.readImage(Unknown Source)
        at com.sun.imageio.plugins.png.PNGImageReader.read(Unknown Source)
        at javax.imageio.ImageIO.read(Unknown Source)
        at javax.imageio.ImageIO.read(Unknown Source)
        at de.uka.ipd.idaho.gamta.util.imaging.PageImage.readImage(PageImage.java:431)
        at de.uka.ipd.idaho.gamta.util.imaging.PageImage.<init>(PageImage.java:93)
        at de.uka.ipd.idaho.gamta.util.imaging.PageImageSource$AbstractPageImageSource.getPageImage(PageImageSource.java:117)
        at de.uka.ipd.idaho.gamta.util.imaging.PageImageSource$AbstractPageImageSource.getPageImage(PageImageSource.java:126)
        at de.uka.ipd.idaho.im.pdf.PdfExtractor$8.doFor(PdfExtractor.java:1868)
        at de.uka.ipd.idaho.gamta.util.ParallelJobRunner$ParallelForJob.run(ParallelJobRunner.java:245)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException
        at javax.imageio.stream.ImageInputStreamImpl.readInt(Unknown Source)
        ... 12 more

**Comment by gsautter** [comment]
Checking it right now, but this exception looks a lot like an attempt at loading a page image that was generated and only partially stored on an earlier conversion attempt. I bet if you clean out the page image cache, this exception will go away.

Apart from that, I suggest you use the new batch parameters to speed up processing:
`java -jar -Xmx4096m GgImagineBatch.jar "DATA=D:\diglib\zootaxa\2017\temp1" DT=BD CACHE=./BatchCache FM=D CS=S`
Of course you can replace `./BatchCache` with another caching folder of your choice. Anyway, specifying a cache makes the batch store intermediate results, i.e., if the materials citations throw an exception, you still have persisted the document state right before starting the materials citation handler. And if you re-start the batch on the same PDF, it will pick up right there.
Further, `FM=D` sets font handling to "decode", and `CS=S` sets the characters considered in font decoding to "Latin full + scientific symbols", i.e., all Latin characters and derived diacritics, plus symbols like male and female.

For printing the full set of options, simply run `java -jar GgImagineBatch.jar HELP`

**Comment by gsautter** [comment]
And while I was typing the explanation of the newly added options (since Monday's build), the file processed just fine.

**Comment by myrmoteras** [comment]
Ok – this worked and the files are processed. Also the code below seem to work – see today’s species (Aug 18,2017)
