### ISSUE TITLE
Zootaxa processing error logs

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#493]
@gsautter I run todays Zootaxa, and here is the error log. The is attached did not work. ...2.pdf is too large to upload

[GgImagineBatch.20180919-1541.err.zip](https://github.com/gsautter/goldengate-imagine/files/2397615/GgImagineBatch.20180919-1541.err.zip)
[zootaxa.4482.3.1.pdf](https://github.com/gsautter/goldengate-imagine/files/2397620/zootaxa.4482.3.1.pdf)
[zootaxa.4482.3.6.pdf](https://github.com/gsautter/goldengate-imagine/files/2397621/zootaxa.4482.3.6.pdf)
[zootaxa.4482.3.9.pdf](https://github.com/gsautter/goldengate-imagine/files/2397626/zootaxa.4482.3.9.pdf)
[zootaxa.4482.3.10.pdf](https://github.com/gsautter/goldengate-imagine/files/2397627/zootaxa.4482.3.10.pdf)

[zootaxa.4482.3.3.pdf](https://github.com/gsautter/goldengate-imagine/files/2397629/zootaxa.4482.3.3.pdf)

**Comment by gsautter** [comment]
I stumbled upon the same this morning and fixed it already. Will tray and make sure to provide an update with the fix tonight.

**Comment by myrmoteras** [comment]
@gsautter got the latest built, but ...1.pdf still does not work

**Comment by gsautter** [comment]
Got a log? Might be helpful to see what changed.

**Comment by myrmoteras** [comment]
![image](https://user-images.githubusercontent.com/4609956/45779674-f4ce3280-bc5b-11e8-99e4-c60ccef489f3.png)

**Comment by gsautter** [comment]
OK, that was a different issue altogether, one that only comes to bear in the presence of keys. I've uploaded an update with a fix for that as well.

**Comment by myrmoteras** [comment]
@gsautter 

where are the documents from the previous batch stored

Processing document 'D:\diglib\zootaxa\temp3\zootaxa.4482.3.1.pdf'
 - document restored from previous batch run

**Comment by gsautter** [comment]
The intermediate results are in `<GGI>/BatchCache/TempDocs`. No need to delete anything, though, documents are stored only between whole batch steps.

If you want to start from there in GGI, on the other hand, you can use the recently added "Batch Cached Documents" on the `Entries.txt` file inside the cached document folder.

**Comment by myrmoteras** [comment]
now it is much better
![image](https://user-images.githubusercontent.com/4609956/45781989-dec37080-bc61-11e8-94a8-47036e1816d4.png)

still 9.pdf does not work

D:\GoldenGateImagine20180807>java -jar -Xmx10240m GgImagineBatch.jar "DATA=D:\diglib\zootaxa\temp4" DT=D CACHE=./BatchCache FM=R
Loading parameters
GoldenGATE Imagine core created, configuration is Default.imagine
Image Markup Tool 'StructureDetector' loaded
Image Markup Tool 'MetaDataAdder' loaded
Image Markup Tool 'KeyHandler' loaded
Image Markup Tool 'ParseBibliography.imTool' loaded
Image Markup Tool 'MarkBibRefCitations.imTool' loaded
Image Markup Tool 'MarkTaxonNames.imTool' loaded
Image Markup Tool 'TableAnnotCleaner' loaded
Image Markup Tool 'RemoveDuplicateAnnots' loaded
Image Markup Tool 'TreatmentTaggerStyled.imTool' loaded
Image Markup Tool 'ExtractMaterialsCitations.imTool' loaded
Image Markup Tool 'CheckAnnotNesting' loaded
Processing document 'D:\diglib\zootaxa\temp4\zootaxa.4482.3.9.pdf'
 - loaded PDF of 1558908 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Removing vertical watermarks on page margins
Assessing page content
Handling flipped page content
Analyzing words in relation to figures and graphics
Error processing document 'D:\diglib\zootaxa\temp4\zootaxa.4482.3.9.pdf': null
java.lang.NullPointerException
        at de.uka.ipd.idaho.im.pdf.PdfColorSpace.getColorSpace(PdfColorSpace.java:165)
        at de.uka.ipd.idaho.im.pdf.PdfExtractor.decodeBitmap(PdfExtractor.java:10371)
        at de.uka.ipd.idaho.im.pdf.PdfExtractor.decodeOther(PdfExtractor.java:10342)
        at de.uka.ipd.idaho.im.pdf.PdfExtractor.decodeImage(PdfExtractor.java:10228)
        at de.uka.ipd.idaho.im.pdf.PdfExtractor.getFigureImage(PdfExtractor.java:926)
        at de.uka.ipd.idaho.im.pdf.PdfExtractor.storeFiguresAsSupplements(PdfExtractor.java:4909)
        at de.uka.ipd.idaho.im.pdf.PdfExtractor.access$1000(PdfExtractor.java:158)
        at de.uka.ipd.idaho.im.pdf.PdfExtractor$8.doFor(PdfExtractor.java:1988)
        at de.uka.ipd.idaho.gamta.util.ParallelJobRunner$ParallelForJob.run(ParallelJobRunner.java:245)
        at java.lang.Thread.run(Unknown Source)

D:\GoldenGateImagine20180807>
[GgImagineBatch.20180919-2314.err.log](https://github.com/gsautter/goldengate-imagine/files/2398758/GgImagineBatch.20180919-2314.err.log)
[GgImagineBatch.20180919-2314.out.log](https://github.com/gsautter/goldengate-imagine/files/2398759/GgImagineBatch.20180919-2314.out.log)

**Comment by myrmoteras** [comment]
[zootaxa.4482.3.9.pdf](https://github.com/gsautter/goldengate-imagine/files/2398761/zootaxa.4482.3.9.pdf)

**Comment by gsautter** [comment]
Implemented, thanks for the example. Looks like we have yet another rare case covered now.

Fix comes with next GGI core update.
