### ISSUE TITLE
batch problems: don't work

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#501]
@gsautter can you please run these files in your system as batch? They don't work here run this

java -jar -Xmx10240m GgImagineBatch.jar "DATA=E:\diglib\zootaxa\temp" CACHE=./BatchCache FM=U

https://drive.google.com/open?id=1zuD8LbnBy4uixmNgBslkCENXOtfW0bP3

**Comment by gsautter** [comment]
Will do.

**Comment by myrmoteras** [comment]
I added some more files, you can also see what did and what did not work here https://docs.google.com/spreadsheets/d/1q-VskOXT87Qt_Mj1MNjGFZOdCKq4UDDQgxTe6WXaxDs/edit#gid=0 all that marked in orange did not work. These are not showstoppers, but just did not process.

**Comment by myrmoteras** [comment]
some more from 80 processed articles today in the above directory

**Comment by gsautter** [comment]
I've been all over this all day ... something really strange is going on here. And I'm trying hard to figure out what.

**Comment by gsautter** [comment]
Especially in longer documents, it seems reference tagging (not parsing) is going on some kind of a combinatoric rampage ... figuring out counter measures.

**Comment by gsautter** [comment]
And only a few PDFs after I figured it might help to pre-filter paragraphs by the number of words they contain (by a maximum), zootaxa.4476.1.4.pdf comes up with a reference to a Nature article with some 40 to 50 authors explicitly listed ... afraid I'll have to find some other way of handling such behemoths.

**Comment by gsautter** [comment]
Guess I was estimating a little too conservatively ... that reference has 171 (!!!) author names explicitly listed ...

**Comment by myrmoteras** [comment]
here is one more monograph that did not work today, 
[zootaxa.4487.1.1.pdf](https://github.com/gsautter/goldengate-imagine/files/2441264/zootaxa.4487.1.1.pdf)

**Comment by myrmoteras** [comment]
@gsautter how do you want to proceed with the nonprocessing PDFs? I just keep adding PDFs to the directory https://docs.google.com/spreadsheets/d/1q-VskOXT87Qt_Mj1MNjGFZOdCKq4UDDQgxTe6WXaxDs/edit#gid=0 

Please explain me how you envision to get them processed. Shall I a wait until a new built comes and then run them all again? Or will you process them and then let me know?

**Comment by gsautter** [comment]
Well, since my only way of figuring out why these PDFs don't process is to run them, is there all too much of a point in you running them again later? Some of them are pretty large ... 
Question is how I pass you the (even larger) IMFs to do whatever checks you do before uploading them. What's the limitation on the Google Drive?

**Comment by gsautter** [comment]
On the plus side, I got all but 2 in the trouble folder processing now, working hard to get the remaining 2 to run.

**Comment by myrmoteras** [comment]
I guess, the best would be to run them again to see, whether the new build is ok. Because otherwise I have to go through the document stepwise and that takes more time.

If they process fine, then you might as well upload them to BLR. The only thing you might want to check by opening the IMF is to see whether the fonts are alright and all the figures caption have been discovered.
Other errors I assume we can check later.
In this case, you need me just let know which articles you have processed by providing a list of UUIDs

**Comment by gsautter** [comment]
OK, I'll try and fix the remaining 2, then make a new build.

Once you tell me the new build works fine, either one of us can upload them.

**Comment by gsautter** [comment]
One more down, just a materials citation runaway to go (zootaxa.4470.1.1.pdf).

**Comment by myrmoteras** [comment]
why does it take time to make a new built? why can't you just create a new built once you fixed a bug?

**Comment by myrmoteras** [comment]
here more 
this is a showstopper: 
[zootaxa.4454.1.7.pdf](https://github.com/gsautter/goldengate-imagine/files/2449587/zootaxa.4454.1.7.pdf)

**Comment by gsautter** [comment]
You're right ... new build is out, and processed the latest error file (zootaxa.4454.1.7.pdf) just fine.

It's just the occasional materials citation runaway pending now.

**Comment by myrmoteras** [comment]
@gsautter I am running all the files again https://drive.google.com/open?id=1zuD8LbnBy4uixmNgBslkCENXOtfW0bP3

I stopped after the first 3 that do not work.


zootaxa.4444.5.3 does not work
Running Image Markup Tool 'Parse Bibliography'
Wrapping document
Checking document
Loading document processor
Error processing document 'E:\diglib\zootaxa\temp28\zootaxa.4444.5.3.pdf': Annotation size out of bounds: 0
java.lang.RuntimeException: Annotation size out of bounds: 0
        at de.uka.ipd.idaho.gamta.Gamta.newAnnotation(Gamta.java:415)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.trimUrlOrDoi(RefParse.java:2404)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.getBrokenURLsAndDOIs(RefParse.java:2334)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.getBaseDetails(RefParse.java:2215)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.parseBibRefs(RefParse.java:973)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.parseBibRefs(RefParse.java:944)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParseInteractive.processBibRefs(RefParseInteractive.java:41)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParseInteractive.processBibRefs(RefParseInteractive.java:36)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParseAnalyzer.process(RefParseAnalyzer.java:59)
        at de.uka.ipd.idaho.goldenGate.plugin.analyzers.AnalyzerManager$AnalyzerDocumentProcessor.process(AnalyzerManager.java:207)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:329)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:295)
        at de.uka.ipd.idaho.im.imagine.plugins.tools.ImageMarkupToolManager$DpImageMarkupTool.process(ImageMarkupToolManager.java:549)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:703)
...................

Processing document 'E:\diglib\zootaxa\temp28\zootaxa.4445.1.1.pdf'
 - document restored from previous batch run
 - assigned document style 'zootaxa.2013.monograph'
Skipping previously-run Image Markup Tool 'Detect Document Structure'
Skipping previously-run Image Markup Tool 'Add Document Meta Data'
Skipping previously-run Image Markup Tool 'Mark Taxonomic Keys'
Running Image Markup Tool 'Parse Bibliography'
Wrapping document
Checking document
Loading document processor
Error processing document 'E:\diglib\zootaxa\temp28\zootaxa.4445.1.1.pdf': GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOf(Unknown Source)
        at java.util.Vector.grow(Unknown Source)
        at java.util.Vector.ensureCapacityHelper(Unknown Source)
        at java.util.Vector.addElement(Unknown Source)
        at de.uka.ipd.idaho.stringUtils.StringVector.addElement(StringVector.java:108)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse$Structure.<init>(RefParse.java:4895)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.getStructures(RefParse.java:2650)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.getStructures(RefParse.java:2672)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.getStructures(RefParse.java:2672)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.getStructures(RefParse.java:2672)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.getStructures(RefParse.java:2672)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.getStructures(RefParse.java:2643)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.parseBibRefs(RefParse.java:1063)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.parseBibRefs(RefParse.java:944)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParseInteractive.processBibRefs(RefParseInteractive.java:41)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParseInteractive.processBibRefs(RefParseInteractive.java:36)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParseAnalyzer.process(RefParseAnalyzer.java:59)
        at de.uka.ipd.idaho.goldenGate.plugin.analyzers.AnalyzerManager$AnalyzerDocumentProcessor.process(AnalyzerManager.java:207)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:329)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:295)
        at de.uka.ipd.idaho.im.imagine.plugins.tools.ImageMarkupToolManager$DpImageMarkupTool.process(ImageMarkupToolManager.java:549)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:703)
Processing document 'E:\diglib\zootaxa\temp28\zootaxa.4446.2.1.pdf'
 - document restored from previous batch run
 - assigned document style 'zootaxa.2013.journal_article'
Skipping previously-run Image Markup Tool 'Detect Document Structure'
Skipping previously-run Image Markup Tool 'Add Document Meta Data'
Skipping previously-run Image Markup Tool 'Mark Taxonomic Keys'
Running Image Markup Tool 'Parse Bibliography'
Wrapping document
Checking document
Loading document processor
Error processing document 'E:\diglib\zootaxa\temp28\zootaxa.4446.2.1.pdf': Annotation size out of bounds: 0
java.lang.RuntimeException: Annotation size out of bounds: 0
        at de.uka.ipd.idaho.gamta.Gamta.newAnnotation(Gamta.java:415)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.trimUrlOrDoi(RefParse.java:2404)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.getBrokenURLsAndDOIs(RefParse.java:2334)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.getBaseDetails(RefParse.java:2215)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.parseBibRefs(RefParse.java:973)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParse.parseBibRefs(RefParse.java:944)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParseInteractive.processBibRefs(RefParseInteractive.java:41)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParseInteractive.processBibRefs(RefParseInteractive.java:36)
        at de.uka.ipd.idaho.plugins.bibRefs.refParse.RefParseAnalyzer.process(RefParseAnalyzer.java:59)
        at de.uka.ipd.idaho.goldenGate.plugin.analyzers.AnalyzerManager$AnalyzerDocumentProcessor.process(AnalyzerManager.java:207)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:329)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:295)
        at de.uka.ipd.idaho.im.imagine.plugins.tools.ImageMarkupToolManager$DpImageMarkupTool.process(ImageMarkupToolManager.java:549)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:703)
Processing document 'E:\diglib\zootaxa\temp28\zootaxa.4449.1.1.pdf'
 - document restored from previous batch run
 - assigned document style 'zootaxa.2013.monograph'
Skipping previously-run Image Markup Tool 'Detect Document Structure'
Skipping previously-run Image Markup Tool 'Add Document Meta Data'
Skipping previously-run Image Markup Tool 'Mark Taxonomic Keys'
Running Image Markup Tool 'Parse Bibliography'
Wrapping document
Checking document
Loading document processor

**Comment by gsautter** [comment]
The "Annotation size out of bounds: 0" also is a bibliography issue, namely a glitch in broken URL recovery, but one I fixed a good bit ago ...

The materials citations are next.

For the bibliography issues, and other things that appear to re-surface a good while after fixing, I've just created a full new build. Let's hope this finally leaves past bugs in the past.

**Comment by myrmoteras** [comment]
ok - I am running with the new download the remaining files again.

these don't work and hung 
materialsCitation issue
zootaxa.4462.2.2
zootaxa.4470.1.1 (this is a paper with very densely packed mc. It run a couple of MC and then stalled 

don't process
zootaxa.4466.1.16

**Comment by gsautter** [comment]
Sorry for the two with the materials citations. As mentioned above, I'll take on these next. The other two I'll check out.

**Comment by gsautter** [comment]
The other two (zootaxa.4466.1.16 and zootaxa.4472.3.11) actually process just fine. The two error messages in the end are merely due to a failed (local) DwC-A export, which is additional to the processing result. We added that for demo purposes originally, and could easily remove it without incurring any changes in the resulting IMF proper.

The failure messages for DwC-A creation are somewhat different, though:
- The one for zootaxa.4466.1.16 simply states that there are no treatments, which, looking at the PDF, is spot-on, as there aren't any.
- The one for zootaxa.4472.3.11 complains about invalid metadata, which might well be due to the fact that it's an erratum, whose layout may deviate from an article and thus elude the style template (the arrangement of author names and title jump my eye here). Plus, that one doesn't contain any treatments, either.

**Comment by myrmoteras** [comment]
more materialsCitation
zootaxa.4358.1.2

**Comment by myrmoteras** [comment]
The other two (zootaxa.4466.1.16 and zootaxa.4472.3.11) 
they did not process here, so you might process them and upload to BLR?!

**Comment by gsautter** [comment]
Thanks for the additional materials citation test case.

For the other two (zootaxa.4466.1.16 and zootaxa.4472.3.11), could you share the batch output? Would be helpful to know where they fail ... I did get an export error, too, see above, but that happens _after_ processing is finished (and has no detrimental effect at all) - it merely states "cannot export DwC-A for lack of treatments".

**Comment by myrmoteras** [comment]
this one has a font error, even using the latest build
![image](https://user-images.githubusercontent.com/4609956/46760884-79e4be80-ccd3-11e8-848f-ae19ba586327.png)
zootaxa.4438.3.3

**Comment by myrmoteras** [comment]
additional show stoppers
materialsCitation
zootaxa.4456.1.1

**Comment by myrmoteras** [comment]
I added the batch output to the GGDirectory

**Comment by myrmoteras** [comment]
bibRefs issues?
zt03767p256
