### ISSUE TITLE
ggi batch processing

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#572]
there is a problem with batch processing

Microsoft Windows [Version 10.0.17134.523]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\agost>d:

D:\>cd GoldenGateImagine20180807

D:\GoldenGateImagine20180807>java -jar -Xmx10240m GgImagineBatch.jar "DATA=D:\diglib\zootaxa\temp6" CACHE=./BatchCache FM=U
Loading parameters
GoldenGATE Imagine core created, configuration is Default.imagine
Image Markup Tool 'StructureDetector' loaded
Image Markup Tool 'MetaDataAdder' loaded
Image Markup Tool 'KeyHandler' loaded
Image Markup Tool 'ParseBibliography.imTool' loaded
Image Markup Tool 'MarkBibRefCitations.imTool' loaded
Image Markup Tool 'MarkTaxonNames.imTool' loaded
Image Markup Tool 'TableAnnotCleaner' loaded
Image Markup Tool 'RemoveDuplicateAnnots' loaded
Image Markup Tool 'TreatmentTaggerStyled.imTool' loaded
Image Markup Tool 'ExtractMaterialsCitations.imTool' loaded
Image Markup Tool 'CheckAnnotNesting' loaded
Processing document 'D:\diglib\zootaxa\temp6\zootaxa.4551.5.1.pdf'
 - loaded PDF of 21722808 bytes
Error processing document 'D:\diglib\zootaxa\temp6\zootaxa.4551.5.1.pdf': For input string: "Internal"
java.lang.NumberFormatException: For input string: "Internal"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
        at java.lang.Double.parseDouble(Unknown Source)
        at java.lang.Double.<init>(Unknown Source)
        at de.uka.ipd.idaho.im.pdf.PdfParser.cropNext(PdfParser.java:666)
        at de.uka.ipd.idaho.im.pdf.PdfParser.cropHashtable(PdfParser.java:927)
        at de.uka.ipd.idaho.im.pdf.PdfParser.cropNext(PdfParser.java:574)
        at de.uka.ipd.idaho.im.pdf.PdfParser.cropHashtable(PdfParser.java:927)
        at de.uka.ipd.idaho.im.pdf.PdfParser.cropNext(PdfParser.java:574)
        at de.uka.ipd.idaho.im.pdf.PdfParser.parseObject(PdfParser.java:512)
        at de.uka.ipd.idaho.im.pdf.PdfParser.getObjects(PdfParser.java:139)
        at de.uka.ipd.idaho.im.pdf.PdfExtractor.doLoadGenericPdf(PdfExtractor.java:485)
        at de.uka.ipd.idaho.im.pdf.PdfExtractor.loadGenericPdf(PdfExtractor.java:473)
        at de.uka.ipd.idaho.im.pdf.PdfExtractor.loadGenericPdf(PdfExtractor.java:351)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:640)
Processing document 'D:\diglib\zootaxa\temp6\zootaxa.4551.5.2.pdf'
 - loaded PDF of 661607 bytes
Extracting page content
Assessing font char usage
Importing page words

[GgImagineBatch.20190206-2358.err.zip](https://github.com/gsautter/goldengate-imagine/files/2838644/GgImagineBatch.20190206-2358.err.zip)

**Comment by gsautter** [comment]
Looks like some weird entry in the PDF where there should be a number ... will have to check in the PDF proper.

**Comment by gsautter** [comment]
Reproduced ... will check how this happens.

**Comment by gsautter** [comment]
PDF ends in some HTML snippet stating "500 Internal Server Error" ... this is a broken download, not even a real error in the PDF.
