### ISSUE TITLE
error log: interpretation

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#606]
@gsautter is this an error message, and if so, what does it mean?

Finishing export
Error exporting document 'E:\diglib\zootaxa\temp36\zootaxa.4508.2.5.pdf' via 'Export Error Protocol': de/uka/ipd/idaho/im/util/ImDocumentErrorProtocol
java.lang.NoClassDefFoundError: de/uka/ipd/idaho/im/util/ImDocumentErrorProtocol
        at de.uka.ipd.idaho.goldenGateServer.plazi.imagine.ErrorProtocolDocumentExporter.exportDocument(ErrorProtocolDocumentExporter.java:196)
        at de.uka.ipd.idaho.goldenGateServer.plazi.imagine.ErrorProtocolDocumentExporter.exportDocument(ErrorProtocolDocumentExporter.java:190)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:771)
Preparing caption data
Preparing export file
Exporting captions
Exporting caption target objects
Finishing export

**Comment by myrmoteras** [comment]
may be you can explain how to read the error logs. Right now, it seems there are plenty of IMFs with error messages which seems to be often the same?

Error exporting document 'E:\diglib\zootaxa\temp37\zootaxa.4514.1.3.pdf' via 'Export Error Protocol': de/uka/ipd/idaho/im/util/ImDocumentErrorProtocol
java.lang.NoClassDefFoundError: de/uka/ipd/idaho/im/util/ImDocumentErrorProtocol
        at de.uka.ipd.idaho.goldenGateServer.plazi.imagine.ErrorProtocolDocumentExporter.exportDocument(ErrorProtocolDocumentExporter.java:196)
        at de.uka.ipd.idaho.goldenGateServer.plazi.imagine.ErrorProtocolDocumentExporter.exportDocument(ErrorProtocolDocumentExporter.java:190)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:771)

**Comment by gsautter** [comment]
That's the terminal export of the error log going wrong, for some weird reason that should have been fixed with the latest update (Monday last week).
It does _not_ compromise the resulting IMF proper, however, just the exports that happen after an IMF is complete. In that regard, it's not as much of a problem unless you plan on using the QC tool, which was also included in the aforementioned update.

**Comment by gsautter** [comment]
In general, "Error exporting document ..." does not compromise the IMFs, only "Error processing document ..." does that in that it leaves the processing unfinished in the batch cache.
