### ISSUE TITLE
GGI does not work with EJT

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#69]
@gsautter this artilce from EJt odes not work with the current version of GGI. It stops somehwere inbetween.

Font 'FreeSerif' loaded successfully.
Font 'FreeSerifItalic' loaded successfully.
Font 'FreeSerifBold' loaded successfully.
Font 'FreeSerifBoldItalic' loaded successfully.
Font 'FreeSans' loaded successfully.
Font 'FreeSansOblique' loaded successfully.
Font 'FreeSansBold' loaded successfully.
Font 'FreeSansBoldOblique' loaded successfully.
Font 'FreeMono' loaded successfully.
Font 'FreeMonoOblique' loaded successfully.
Font 'FreeMonoBold' loaded successfully.
Font 'FreeMonoBoldOblique' loaded successfully.
Feb 15, 2017 2:44:47 PM org.icepdf.core.pobjects.Catalog <clinit>
INFO: ICEsoft ICEpdf Core 4.2.0 
Exception in thread "LoaderThread" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor.storeGraphicsAsSupplements(PdfExtractor.java:4385)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor.access$600(PdfExtractor.java:157)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor$6.doFor(PdfExtractor.java:1567)
	at de.uka.ipd.idaho.gamta.util.ParallelJobRunner$ParallelForJob.run(ParallelJobRunner.java:245)
	at java.lang.Thread.run(Unknown Source)

as well as with the version before

Font 'FreeSerif' loaded successfully.
Font 'FreeSerifItalic' loaded successfully.
Font 'FreeSerifBold' loaded successfully.
Font 'FreeSerifBoldItalic' loaded successfully.
Font 'FreeSans' loaded successfully.
Font 'FreeSansOblique' loaded successfully.
Font 'FreeSansBold' loaded successfully.
Font 'FreeSansBoldOblique' loaded successfully.
Font 'FreeMono' loaded successfully.
Font 'FreeMonoOblique' loaded successfully.
Font 'FreeMonoBold' loaded successfully.
Font 'FreeMonoBoldOblique' loaded successfully.
Feb 15, 2017 2:50:10 PM org.icepdf.core.pobjects.Catalog <clinit>
INFO: ICEsoft ICEpdf Core 4.2.0 
Exception in thread "LoaderThread" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor.storeGraphicsAsSupplements(PdfExtractor.java:4385)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor.access$600(PdfExtractor.java:157)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor$6.doFor(PdfExtractor.java:1567)
	at de.uka.ipd.idaho.gamta.util.ParallelJobRunner$ParallelForJob.run(ParallelJobRunner.java:245)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "LoaderThread" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor.storeGraphicsAsSupplements(PdfExtractor.java:4385)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor.access$600(PdfExtractor.java:157)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor$6.doFor(PdfExtractor.java:1567)
	at de.uka.ipd.idaho.gamta.util.ParallelJobRunner$ParallelForJob.run(ParallelJobRunner.java:245)
	at java.lang.Thread.run(Unknown Source)

but it works with the version I have from 
[274-2017.pdf](https://github.com/gsautter/goldengate-imagine/files/777794/274-2017.pdf)

**Comment by gsautter** [comment]
Decodes just fine with the latest fixes ...
