### ISSUE TITLE
[Template] We did something wrong, I suppose

### ISSUE THREAD

**Issue by mguidoti** [gsautter/goldengate-imagine#834]
Hi Guido,

As you know, we're creating the Zoosystema template - and everything was working just fine, in fact, fine enough to considered it finished. However, when we start 'running the steps' in a Zoosystema document loaded, with the template loaded (anchor working), we start getting all kinds of errors, like:

* Detect Document Structure:
![image](https://user-images.githubusercontent.com/44419136/71018742-ceee4280-20d7-11ea-93d3-4c741d3573b3.png)

* Parse Bibliography
![image](https://user-images.githubusercontent.com/44419136/71018766-dc0b3180-20d7-11ea-9ec3-cc0b6073caf8.png)

Here's the link to the PDF: https://drive.google.com/file/d/1CZ8yTBBCm82HWMmcm6Ml_K344-b5SXHa/view?usp=sharing

Here's our template: https://drive.google.com/file/d/1sLuM4Uscbp_sEntFbtt3f0BHgcj0GNmD/view?usp=sharing

Let me know if you can't access one of both of these files... 

Thanks and sorry for bothering you.

**Comment by gsautter** [comment]
OK, this is weird ... and I don't think this has anything to do with the template ... got a log file for me? They tend to help a great deal with such processing errors.

**Comment by mguidoti** [comment]
Sure: https://drive.google.com/file/d/1ZcmaxBOSLy8qF3TcCIYb0BEKyVMHuQ8-/view?usp=sharing

Thanks for looking at this.

**Comment by gsautter** [comment]
Are you sure you are running the latest build? The line numbers in the logs are nowhere near what they could possible be at the moment ...

**Comment by mguidoti** [comment]
We never skip updates when starting GGI, but I haven't downloaded it again from the website.

How can we check that?

**Comment by gsautter** [comment]
First, please go to your GGI root folder and open `UpdateHosts.cnfg` - does that file contain a line `http://tb.plazi.org/GgServer/Updates`? If not, please put it there and start GGI again.

**Comment by gsautter** [comment]
What you can see on startup is the modification date of the "Default.imagine" configuration, which right now should be Fri, Dec 13, 2019 (if in another syntax).

**Comment by mguidoti** [comment]
> First, please go to your GGI root folder and open `UpdateHosts.cnfg` - does that file contain a line `http://tb.plazi.org/GgServer/Updates`? If not, please put it there and start GGI again.

Yes. Here's its full content:

``` 
http://srv1.plazi.org/GgServer/Updates
http://plazi.cs.umb.edu/GgServer/Updates
http://plazi2.cs.umb.edu/GgServer/Updates
```

**Comment by mguidoti** [comment]
> What you can see on startup is the modification date of the "Default.imagine" configuration, which right now should be Fri, Dec 13, 2019 (if in another syntax).

![image](https://user-images.githubusercontent.com/44419136/71022274-df55eb80-20de-11ea-82af-929a74b33264.png)

**Comment by gsautter** [comment]
`UpdateHosts.cnfg`should just have a single line `http://tb.plazi.org/GgServer/Updates` at this point, can you change that?
Also, `ConfigHosts.cnfg` should only have one line `https://tb.plazi.org/GgServer/Configurations`, please change that as well.

**Comment by gsautter** [comment]
Meanwhile, I decoded the PDF with the template and was indeed able to reproduce the error ... the problem appears to be the omission of leading meta pages, which seems to incur a numbering problem somewhere. I'll make sure to fix that, test the whole process, and put out an update.

**Comment by mguidoti** [comment]
> `UpdateHosts.cnfg`should just have a single line `http://tb.plazi.org/GgServer/Updates` at this point, can you change that?
> Also, `ConfigHosts.cnfg` should only have one line `https://tb.plazi.org/GgServer/Configurations`, please change that as well.

Yes, absolutely. I already did and it's already fixed:

![image](https://user-images.githubusercontent.com/44419136/71022600-9d797500-20df-11ea-8da4-401af13d18a9.png)

I'll fix on the other machines.

Thanks!

**Comment by mguidoti** [comment]
> Meanwhile, I decoded the PDF with the template and was indeed able to reproduce the error ... the problem appears to be the omission of leading meta pages, which seems to incur a numbering problem somewhere. I'll make sure to fix that, test the whole process, and put out an update.

Yes, I did some tests by loading the pdf without ignoring the two initial pages (that parameter on the layout part of the template) and it worked. I think you're definitely on the right track.

Thanks very much for looking at this. I'll go forward and work on the templates for Adansonia, Geodiversitas and Anthropozoologica, the other three MNHN journals Donat requested in the meanwhile. All four journals have these two cover pages, so your fix will be extremely useful and important for this mission Donat gave us.

Thanks!

**Comment by mguidoti** [comment]
Guido, 

Should I just go with these selections?

![image](https://user-images.githubusercontent.com/44419136/71023231-0c0b0280-20e1-11ea-90f8-5923118d008c.png)

**Comment by gsautter** [comment]
That's a good setting ... it basically means how the update should treat data that was downloaded into your local copy of a configuration via web lookups, and moving it along preserves it, preventing duplicate downloads, while also preventing duplication, saving space. Duplication is what happens with the "Copy Over" option, the default before introducing the more flexible handling and this associated option dialog.

**Comment by mguidoti** [comment]
More on this FYI:

If I've the template file in the `GGI\Configurations\Default.imagine\Plugins\DocumentStyleProviderData` folder, the Zoosystema PDFs don't load. 

If I remove this file, and if I remove the `layout.coverPageCount = "2";` parameter I suspect, I can load the PDFs again.

**Comment by gsautter** [comment]
When I tried, actual conversion worked well even with `layout.coverPageCount = "2";` and the errors only started in document structure detection, but yes, removing that line from the template will surely make it behave like normal.

**Comment by mguidoti** [comment]
Ok, but we need this as Zoosystema and the other three MNHN journals Donat asked me to create templates have these 2 cover pages.

Should I do something differently from my end?

Thanks, Guido.

**Comment by gsautter** [comment]
Nope, as I created that fix I announced yesterday, and will put it out soon, as I'm in the middle of testing it right now. All you have to do then is restart GGI and let the auto-update do its work.

**Comment by mguidoti** [comment]
Awesome Guido.

Thanks for your support and attention!

**Comment by gsautter** [comment]
The update is tested and available, you'll get it when starting up GGI tomorrow. There is also a an update to "Default.imagine" to go with it.

**Comment by mguidoti** [comment]
Awesome, Guido! 

Thank you very much!

**Comment by mguidoti** [comment]
Just to report a few things:

I've all machines updated, apparently. However, one of the four machines didn't got the following warning dialog:

![image](https://user-images.githubusercontent.com/44419136/71191352-09391a80-2265-11ea-8b0d-fe8e743be6c2.png)

But its `default.imagine` date is the same as in the other three machines.

Moreover, every time I re-start GGI he asks me to download the same update now. Not sure if this is the expected behavior...?

And finally, there is one Zoosystema paper that I couldn't load in any machine. Here's the link to the [PDF](https://drive.google.com/file/d/1at_6TyWGdZuAmUwgwtKzZx2zQLmpPbq1/view?usp=sharing), and the link to my latest [*.log](https://drive.google.com/file/d/1uK3fg8RNG16qoX5Mx68LTHnZm2DU2R8c/view?usp=sharing).

Let me know if there is something I can do from here.

Thanks once again!

**Comment by gsautter** [comment]
The question dialog comes up when you select a local configuration _and_ there is a more recent version of the same configuration on one of the configured config hosts ... it's not really a warning, just a question. If you select the remote configuration, it will ask you whether or not you want to make a local copy of it (or update a less recent local configuration) and work with that.

The question coming on every GGI startup is strange, though ... once it is updated locally, the timestamps should be the same, and there should be no more asking, unless you selected "No" or something went wrong with the update.

**Comment by gsautter** [comment]
About the PDF (and please let's try and not mix _three_ different discussions in one ticket in the future): The log looks perfectly normal, no errors or anything ... which error message did you get?

**Comment by mguidoti** [comment]
> About the PDF (and please let's try and not mix _three_ different discussions in one ticket in the future): The log looks perfectly normal, no errors or anything ... which error message did you get?

No error message, it simply doesn't open the PDF after the 0 to 100% converting progress bar completes. Tried in three machines.

**Comment by gsautter** [comment]
Weird ... I just decoded this PDF, and it opened just fine, have it right in front of me, and you have the same update level now as I do.

There must be _something_ in either of the log files (remember there is `...out.log` and `...err.log`) if a PDF doesn't open.

**Comment by mguidoti** [comment]
I shared te *.log. Here's my entire *.err:

```
Font 'FreeSerif' loaded successfully.
Font 'FreeSerifItalic' loaded successfully.
Font 'FreeSerifBold' loaded successfully.
Font 'FreeSerifBoldItalic' loaded successfully.
Font 'FreeSans' loaded successfully.
Font 'FreeSansOblique' loaded successfully.
Font 'FreeSansBold' loaded successfully.
Font 'FreeSansBoldOblique' loaded successfully.
Font 'FreeMono' loaded successfully.
Font 'FreeMonoOblique' loaded successfully.
Font 'FreeMonoBold' loaded successfully.
Font 'FreeMonoBoldOblique' loaded successfully.
Dec 19, 2019 1:40:51 PM org.icepdf.core.pobjects.Catalog <clinit>
INFO: ICEsoft ICEpdf Core 4.2.0 
Exception in thread "Thread-45" java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.image.BufferedImage.<init>(Unknown Source)
	at sun.java2d.loops.GraphicsPrimitive.convertFrom(Unknown Source)
	at sun.java2d.loops.GraphicsPrimitive.convertFrom(Unknown Source)
	at sun.java2d.loops.MaskBlit$General.MaskBlit(Unknown Source)
	at sun.java2d.loops.Blit$GeneralMaskBlit.Blit(Unknown Source)
	at sun.java2d.pipe.DrawImage.blitSurfaceData(Unknown Source)
	at sun.java2d.pipe.DrawImage.renderImageCopy(Unknown Source)
	at sun.java2d.pipe.DrawImage.copyImage(Unknown Source)
	at sun.java2d.pipe.DrawImage.copyImage(Unknown Source)
	at sun.java2d.pipe.ValidatePipe.copyImage(Unknown Source)
	at sun.java2d.SunGraphics2D.copyImage(Unknown Source)
	at sun.java2d.pipe.DrawImage.makeBufferedImage(Unknown Source)
	at sun.java2d.pipe.DrawImage.renderImageXform(Unknown Source)
	at sun.java2d.pipe.DrawImage.transformImage(Unknown Source)
	at sun.java2d.pipe.DrawImage.transformImage(Unknown Source)
	at sun.java2d.pipe.ValidatePipe.transformImage(Unknown Source)
	at sun.java2d.SunGraphics2D.drawImage(Unknown Source)
	at sun.java2d.SunGraphics2D.drawRenderedImage(Unknown Source)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor.getFigureImage(PdfExtractor.java:1059)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor.storeFiguresAsSupplements(PdfExtractor.java:5146)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor.access$1000(PdfExtractor.java:157)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor$7.doFor(PdfExtractor.java:2143)
	at de.uka.ipd.idaho.gamta.util.ParallelJobRunner$ParallelForJob.run(ParallelJobRunner.java:278)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-46" java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.image.BufferedImage.<init>(Unknown Source)
	at sun.java2d.loops.GraphicsPrimitive.convertFrom(Unknown Source)
	at sun.java2d.loops.GraphicsPrimitive.convertFrom(Unknown Source)
	at sun.java2d.loops.MaskBlit$General.MaskBlit(Unknown Source)
	at sun.java2d.loops.Blit$GeneralMaskBlit.Blit(Unknown Source)
	at sun.java2d.pipe.DrawImage.blitSurfaceData(Unknown Source)
	at sun.java2d.pipe.DrawImage.renderImageCopy(Unknown Source)
	at sun.java2d.pipe.DrawImage.copyImage(Unknown Source)
	at sun.java2d.pipe.DrawImage.copyImage(Unknown Source)
	at sun.java2d.pipe.ValidatePipe.copyImage(Unknown Source)
	at sun.java2d.SunGraphics2D.copyImage(Unknown Source)
	at sun.java2d.pipe.DrawImage.makeBufferedImage(Unknown Source)
	at sun.java2d.pipe.DrawImage.renderImageXform(Unknown Source)
	at sun.java2d.pipe.DrawImage.transformImage(Unknown Source)
	at sun.java2d.pipe.DrawImage.transformImage(Unknown Source)
	at sun.java2d.pipe.ValidatePipe.transformImage(Unknown Source)
	at sun.java2d.SunGraphics2D.drawImage(Unknown Source)
	at sun.java2d.SunGraphics2D.drawRenderedImage(Unknown Source)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor.getFigureImage(PdfExtractor.java:1059)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor.storeFiguresAsSupplements(PdfExtractor.java:5146)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor.access$1000(PdfExtractor.java:157)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor$7.doFor(PdfExtractor.java:2143)
	at de.uka.ipd.idaho.gamta.util.ParallelJobRunner$ParallelForJob.run(ParallelJobRunner.java:278)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-42" java.lang.OutOfMemoryError: Java heap space
Exception in thread "Thread-44" java.lang.OutOfMemoryError: Java heap space
Exception in thread "Thread-43" java.lang.OutOfMemoryError: Java heap space
Exception in thread "LoaderThread" java.lang.NullPointerException
	at de.uka.ipd.idaho.im.pdf.PdfExtractor$10.doFor(PdfExtractor.java:2634)
	at de.uka.ipd.idaho.gamta.util.ParallelJobRunner$ParallelForJob.run(ParallelJobRunner.java:278)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-155" java.lang.OutOfMemoryError: Java heap space

```

**Comment by gsautter** [comment]
The part `OutOfMemoryError: Java heap space` says it all ... GGI was running out of memory opening the IMF. How many other documents did you have open in GGI at that time? What other applications were running on the machine?

This can also be a configuration thing, though: in your GGI root folder, there is a file `Parameters.cnfg`, which should contain a line starting `MAX_MEMORY=` - the number after the `=` is the number of MB GGI is allowed to use. If the IMF doesn't open despite the machine proper having plenty of RAM to spare, increase that number and you should be OK. `4096` might be a good value to try, indicating a maximum of 4GB RAM.

**Comment by mguidoti** [comment]
Hi Guido,

Augmenting the `MAX_MEMORY` did the trick. We're all in the default settings: 1024. 

I added 8GB as we've 16GB and the machines are not loaded with softwares, neither people are doing several things at the same time to consume the memory like you suggested. 

Now we can all open the PDF. And I did some negative controls as well: tried to open it again in a different machine with the standard 1024 value and nothing else open, and it failed.

Thanks a lot!

**Comment by gsautter** [comment]
Sure ... always happy to help.

**Comment by myrmoteras** [comment]
I use with my 16GB machine 10GB and this works as well
