### ISSUE TITLE
PDF that do not open in GGI

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#88]
The following PDF cannot be opened in GGI version 20170221

a scanned pdf 
[spicer1977a.pdf](https://github.com/gsautter/goldengate-imagine/files/791803/spicer1977a.pdf)
the ABBYY OCRed version
[spicer1977a_OCR.pdf](https://github.com/gsautter/goldengate-imagine/files/791804/spicer1977a_OCR.pdf)

Font 'FreeSerif' loaded successfully.
Font 'FreeSerifItalic' loaded successfully.
Font 'FreeSerifBold' loaded successfully.
Font 'FreeSerifBoldItalic' loaded successfully.
Font 'FreeSans' loaded successfully.
Font 'FreeSansOblique' loaded successfully.
Font 'FreeSansBold' loaded successfully.
Font 'FreeSansBoldOblique' loaded successfully.
Font 'FreeMono' loaded successfully.
Font 'FreeMonoOblique' loaded successfully.
Font 'FreeMonoBold' loaded successfully.
Font 'FreeMonoBoldOblique' loaded successfully.
Feb 22, 2017 12:23:59 AM org.icepdf.core.pobjects.Catalog <clinit>
INFO: ICEsoft ICEpdf Core 4.2.0 
Exception in thread "LoaderThread" java.lang.NullPointerException
	at de.uka.ipd.idaho.im.pdf.PdfParser.getPageFonts(PdfParser.java:2180)
	at de.uka.ipd.idaho.im.pdf.PdfParser.runPageContent(PdfParser.java:2281)
	at de.uka.ipd.idaho.im.pdf.PdfParser.runPageContent(PdfParser.java:2271)
	at de.uka.ipd.idaho.im.pdf.PdfParser.getPageWordChars(PdfParser.java:1972)
	at de.uka.ipd.idaho.im.pdf.PdfExtractor$2.doFor(PdfExtractor.java:698)
	at de.uka.ipd.idaho.gamta.util.ParallelJobRunner$ParallelForJob.run(ParallelJobRunner.java:245)
	at java.lang.Thread.run(Unknown Source)
......................................

**Comment by gsautter** [comment]
see #86 ... very same issue.
